ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_type VARCHAR(32) NOT NULL DEFAULT 'custom';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_city VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cdek_pvz_code VARCHAR(64) NOT NULL DEFAULT '';
